# Site settings
title: Look Ma, no OS!
email: matt@notevenremotelydorky.com
description: > # this means to ignore newlines until "baseurl:"
  This is running on a multi-megabyte sized unikernel against a XEN hypervisor.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mattbajor
github_username:  technolo-g

# Build settings
markdown: kramdown
